repos:
    # Local hooks (our custom hooks)
  - repo: local
    hooks:
      - id: jira-commit-msg
        name: JIRA Commit Message Hook
        entry: hooks/commit-msg
        language: script
        stages: [commit-msg]
        description: Prepends JIRA ticket numbers from branch names to commit messages.

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        description: Remove trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML syntax
      - id: check-json
        description: Check JSON syntax
      - id: check-added-large-files
        description: Prevent large files from being committed
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-case-conflict
        description: Check for files that would conflict in case-insensitive filesystems

  # Python hooks (if you have Python code)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        description: Format Python code with Black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        description: Sort Python imports

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        description: Lint Python code with flake8
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # YAML/JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml, json]
        description: Format YAML and JSON files

  # Terraform formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
        description: Format Terraform files
      - id: terraform_docs
        description: Generate Terraform documentation
      - id: terraform_tflint
        description: Lint Terraform files with TFLint
        args:
          - --args=--format=compact
