repos:
    # Local hooks (our custom hooks)
  - repo: local
    hooks:
      - id: commit-msg
        name: Commit Message
        entry: bash hooks/commit-msg
        language: system
        stages: [commit-msg]
        description: Automatically add JIRA ticket from branch name to commit message

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        description: Remove trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML syntax
      - id: check-json
        description: Check JSON syntax
      - id: check-added-large-files
        description: Prevent large files from being committed
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-case-conflict
        description: Check for files that would conflict in case-insensitive filesystems

  # Python hooks (if you have Python code)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        description: Format Python code with Black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        description: Sort Python imports

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        description: Lint Python code with flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # YAML/JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [yaml, json]
        description: Format YAML and JSON files
