name: Generate PDF Report

description: |
  Generates a professional PDF report using Python reportlab.
  Creates a well-formatted report with tables, styling, and structured data.

inputs:
  report-title:
    description: 'Title of the report'
    required: false
    default: 'Execution Report'
    type: string
  generated-time:
    description: 'Report generation timestamp'
    required: false
    default: ''
    type: string
  repository:
    description: 'GitHub repository name (e.g., owner/repo)'
    required: false
    default: ''
    type: string
  pr-number:
    description: 'Pull request number'
    required: false
    default: ''
    type: string
  pr-title:
    description: 'Pull request title'
    required: false
    default: ''
    type: string
  execution-details:
    description: 'JSON string of execution details (key-value pairs)'
    required: false
    default: '{}'
    type: string
  commit-information:
    description: 'JSON string of commit information (key-value pairs)'
    required: false
    default: '{}'
    type: string
  quality-check:
    description: 'JSON string of quality check results (key-value pairs)'
    required: false
    default: '{}'
    type: string
  pipeline-status:
    description: 'JSON string of pipeline status (key-value pairs)'
    required: false
    default: '{}'
    type: string
  variables:
    description: 'Pipeline variables (aligned text format)'
    required: false
    default: ''
    type: string
  output-filename:
    description: 'Output PDF filename (without .pdf extension)'
    required: false
    default: 'report'
    type: string

outputs:
  pdf-path:
    description: 'Path to the generated PDF file'
    value: ${{ steps.generate.outputs.pdf-path }}

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install reportlab

    - name: Generate PDF Report
      id: generate
      shell: bash
      run: |
        # Activate virtual environment
        source venv/bin/activate

        # Set environment variables for Python script
        export REPORT_TITLE="${{ inputs.report-title }}"
        export GENERATED_TIME="${{ inputs.generated-time }}"
        export REPOSITORY="${{ inputs.repository }}"
        export PR_NUMBER="${{ inputs.pr-number }}"
        export PR_TITLE="${{ inputs.pr-title }}"
        export EXECUTION_DETAILS='${{ inputs.execution-details }}'
        export COMMIT_INFORMATION='${{ inputs.commit-information }}'
        export QUALITY_CHECK='${{ inputs.quality-check }}'
        export PIPELINE_STATUS='${{ inputs.pipeline-status }}'
        export VARIABLES='${{ inputs.variables }}'
        export OUTPUT_FILENAME="${{ inputs.output-filename }}"

        # Run Python script to generate PDF
        python "$GITHUB_ACTION_PATH/generate_pdf_report.py"

        # Output the PDF path
        echo "pdf-path=${{ inputs.output-filename }}.pdf" >> $GITHUB_OUTPUT
