name: 'Determine Account Number'
description: 'Determines AWS account number based on changed files and environment'
inputs:
  changed-files:
    description: 'List of changed files (from changed-files action)'
    required: true
  environment:
    description: 'Environment (dev_account_number/prod_account_number)'
    required: true
outputs:
  account-number:
    description: 'Determined AWS account number'
    value: ${{ steps.account.outputs.account_number }}
runs:
  using: 'composite'
  steps:
    - name: Determine account number using Python
      id: account
      run: |
        # Get the action directory path
        ACTION_DIR="$GITHUB_ACTION_PATH"
        cd "$ACTION_DIR"
        python3 map_accounts.py
      env:
        CHANGED_FILES: ${{ inputs.changed-files }}
        ENVIRONMENT: ${{ inputs.environment }}
      shell: bash
