name: "PR Status Commenter"
description: "Automatically post comments on PRs when checks pass or fail"
inputs:
  required-checks:
    description: "Comma-separated list of required checks to monitor"
    required: false
    default: "pre-commit,terraform-lint"
  success-template:
    description: "Success comment template (supports variables: {{checks}}, {{pr_number}}, {{repo}})"
    required: false
    default: |
      ✅ **All PR checks passed successfully!**

      🎉 Great job! All automated checks have completed successfully:
      {{checks}}

      This PR is ready for review! 🚀

      📋 **Check Results:**
      - [View all checks](https://github.com/{{repo}}/pull/{{pr_number}}/checks)

      *This comment was automatically posted by the PR Status Commenter.*
  failure-template:
    description: "Failure comment template (supports variables: {{checks}}, {{pr_number}}, {{repo}})"
    required: false
    default: |
      ❌ **Some PR checks failed**

      Please review the failed checks and fix any issues before requesting a review.

      📋 **Check Results:**
      - [View all checks](https://github.com/{{repo}}/pull/{{pr_number}}/checks)

      *This comment was automatically posted by the PR Status Commenter.*
  prevent-duplicates:
    description: "Prevent duplicate comments (true/false)"
    required: false
    default: "true"
  include-check-links:
    description: "Include links to check results (true/false)"
    required: false
    default: "true"
  bot-name:
    description: "Bot name for comment signatures"
    required: false
    default: "PR Status Commenter"
  check-suite-id:
    description: "Check suite ID to monitor (optional, will auto-detect if not provided)"
    required: false
    default: ""

outputs:
  commented:
    description: "Whether a comment was posted (true/false)"
    value: ${{ steps.comment.outputs.commented }}
  comment-type:
    description: "Type of comment posted (success/failure/none)"
    value: ${{ steps.comment.outputs.comment-type }}
runs:
  using: "composite"
  steps:
    - name: Comment on PR Status
      id: comment
      shell: bash
      run: |
        # Set up environment
        REQUIRED_CHECKS="${{ inputs.required-checks }}"
        SUCCESS_TEMPLATE="${{ inputs.success-template }}"
        FAILURE_TEMPLATE="${{ inputs.failure-template }}"
        PREVENT_DUPLICATES="${{ inputs.prevent-duplicates }}"
        INCLUDE_CHECK_LINKS="${{ inputs.include-check-links }}"
        BOT_NAME="${{ inputs.bot-name }}"

        # Get PR number from context
        PR_NUMBER="${{ github.event.pull_request.number }}"
        REPO="${{ github.repository }}"

        if [[ -z "$PR_NUMBER" ]]; then
          echo "No PR number found, skipping comment"
          echo "commented=false" >> $GITHUB_OUTPUT
          echo "comment-type=none" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Processing PR #$PR_NUMBER"

        # Get check runs for this PR using GitHub CLI
        CHECK_RUNS=$(gh api repos/$REPO/commits/${{ github.sha }}/check-runs 2>/dev/null || echo '{"check_runs":[]}')

        # Parse required checks
        IFS=',' read -ra REQUIRED_ARRAY <<< "$REQUIRED_CHECKS"

        # Check status of each required check
        ALL_COMPLETED=true
        ALL_SUCCESSFUL=true
        CHECKS_LIST=""

        for check in "${REQUIRED_ARRAY[@]}"; do
          check=$(echo "$check" | xargs)  # trim whitespace
          echo "Checking for: $check"

          # Find matching check runs (check for both exact match and workflow/job pattern)
          CHECK_STATUS=$(echo "$CHECK_RUNS" | jq -r ".check_runs[] | select(.name == \"$check\" or .name | endswith(\"/$check\") or .name | test(\"$check\"; \"i\")) | .status" | head -1)
          CHECK_CONCLUSION=$(echo "$CHECK_RUNS" | jq -r ".check_runs[] | select(.name == \"$check\" or .name | endswith(\"/$check\") or .name | test(\"$check\"; \"i\")) | .conclusion" | head -1)
          CHECK_NAME=$(echo "$CHECK_RUNS" | jq -r ".check_runs[] | select(.name == \"$check\" or .name | endswith(\"/$check\") or .name | test(\"$check\"; \"i\")) | .name" | head -1)

          if [[ -n "$CHECK_NAME" ]]; then
            if [[ "$CHECK_STATUS" != "completed" ]]; then
              ALL_COMPLETED=false
              echo "Check $CHECK_NAME is not completed (status: $CHECK_STATUS)"
            else
              if [[ "$CHECK_CONCLUSION" == "success" ]]; then
                CHECKS_LIST+="- ✅ $CHECK_NAME"$'\n'
              else
                ALL_SUCCESSFUL=false
                CHECKS_LIST+="- ❌ $CHECK_NAME"$'\n'
              fi
            fi
          else
            echo "No check found matching pattern: $check"
            ALL_COMPLETED=false
          fi
        done

        echo "All completed: $ALL_COMPLETED"
        echo "All successful: $ALL_SUCCESSFUL"

        if [[ "$ALL_COMPLETED" != "true" ]]; then
          echo "Not all checks are completed yet"
          echo "commented=false" >> $GITHUB_OUTPUT
          echo "comment-type=none" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Determine comment type and template
        if [[ "$ALL_SUCCESSFUL" == "true" ]]; then
          COMMENT_TYPE="success"
          TEMPLATE="$SUCCESS_TEMPLATE"
          SEARCH_TEXT="✅ All PR checks passed successfully!"
        else
          COMMENT_TYPE="failure"
          TEMPLATE="$FAILURE_TEMPLATE"
          SEARCH_TEXT="❌ Some PR checks failed"
        fi

        # Check for existing comment if prevent_duplicates is enabled
        SHOULD_POST=true
        if [[ "$PREVENT_DUPLICATES" == "true" ]]; then
          EXISTING_COMMENTS=$(gh api repos/$REPO/issues/$PR_NUMBER/comments 2>/dev/null || echo '[]')

          if echo "$EXISTING_COMMENTS" | jq -e ".[] | select(.user.login == \"github-actions[bot]\" and .body | contains(\"$SEARCH_TEXT\"))" > /dev/null; then
            SHOULD_POST=false
            echo "Duplicate comment found, skipping"
          fi
        fi

        if [[ "$SHOULD_POST" == "true" ]]; then
          # Prepare comment body
          COMMENT_BODY=$(echo "$TEMPLATE" | \
            sed "s/{{checks}}/$CHECKS_LIST/g" | \
            sed "s/{{pr_number}}/$PR_NUMBER/g" | \
            sed "s/{{repo}}/$REPO/g" | \
            sed "s/{{bot_name}}/$BOT_NAME/g")

          # Remove check links section if not enabled
          if [[ "$INCLUDE_CHECK_LINKS" != "true" ]]; then
            COMMENT_BODY=$(echo "$COMMENT_BODY" | sed '/📋 \*\*Check Results:\*\*/,/^\*Automated by/d')
          fi

          # Post comment using GitHub CLI
          echo "$COMMENT_BODY" | gh issue comment $PR_NUMBER --repo $REPO --body-file - > /dev/null 2>&1

          if [[ $? -eq 0 ]]; then
            echo "Posted $COMMENT_TYPE comment on PR #$PR_NUMBER"
            echo "commented=true" >> $GITHUB_OUTPUT
            echo "comment-type=$COMMENT_TYPE" >> $GITHUB_OUTPUT
          else
            echo "Failed to post comment"
            echo "commented=false" >> $GITHUB_OUTPUT
            echo "comment-type=$COMMENT_TYPE" >> $GITHUB_OUTPUT
          fi
        else
          echo "commented=false" >> $GITHUB_OUTPUT
          echo "comment-type=$COMMENT_TYPE" >> $GITHUB_OUTPUT
        fi
