name: "PR Status Commenter"
description: "Automatically post comments on PRs when checks pass or fail"
inputs:
  required-checks:
    description: "Comma-separated list of required checks to monitor"
    required: false
    default: "pre-commit,terraform-lint"
  success-template:
    description: "Success comment template (supports variables: {{checks}}, {{pr_number}}, {{repo}})"
    required: false
    default: |
      ✅ All PR checks passed successfully!

      🎉 Great job! All automated checks have completed successfully:
      {{checks}}

      This PR is ready for review! 🚀

      📋 **Check Results:**
      - [View all checks](https://github.com/{{repo}}/pull/{{pr_number}}/checks)

      *Automated by PR Status Commenter*


runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: npm install @actions/core @actions/github

    - name: Run comment script
      shell: bash
      run: node "$GITHUB_ACTION_PATH/comment-script.js"
      env:
        INPUT_REQUIRED_CHECKS: ${{ inputs.required-checks }}
        INPUT_SUCCESS_TEMPLATE: ${{ inputs.success-template }}
        GITHUB_TOKEN: ${{ github.token }}
