name: "Test Actions"
description: "Test all custom actions in the repository"
inputs:
  fetch-depth:
    description: "Git fetch depth for diff calculation"
    required: false
    default: "0"
    type: string
outputs:
  changed-actions:
    description: "List of changed action files"
    value: ${{ steps.find-changes.outputs.files }}
runs:
  using: "composite"
  steps:
    - name: Checkout with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Find changed action files
      id: find-changes
      uses: ./.github/actions/changed-files
      with:
        pattern: "^\\.github/actions/.*/action\\.yml$"

    - name: Show changed actions
      shell: bash
      run: |
        echo "[Info] Changed action files:"
        echo "${{ steps.find-changes.outputs.files }}"

    - name: Test JavaScript actions
      id: test-js
      shell: bash
      run: |
        echo "[Info] 📦 Testing JavaScript actions..."

        # Check if any JavaScript actions exist
        js_actions=""
        for action_file in ${{ steps.find-changes.outputs.files }}; do
          if [[ -n "$action_file" && -f "$action_file" ]]; then
            action_type=$(grep -A1 "runs:" "$action_file" | grep "using:" | awk '{print $2}' | tr -d '"')
            if [[ "$action_type" =~ ^node(16|18|20)$ ]]; then
              echo "[Info] Found JavaScript action: $action_file"
              js_actions="$js_actions $action_file"
            fi
          fi
        done

        if [[ -n "$js_actions" ]]; then
          echo "[Info] JavaScript actions to test: $js_actions"
          echo "js_actions_found=true" >> $GITHUB_OUTPUT
          echo "js_actions_list=$js_actions" >> $GITHUB_OUTPUT

          # Install Node.js if needed
          echo "[Info] Installing Node.js..."
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          echo "[Info] Node.js version: $(node --version)"
          echo "[Info] npm version: $(npm --version)"

          # Test each JavaScript action
          for action_file in $js_actions; do
            echo "[Info] Testing JavaScript action: $action_file"
            action_dir=$(dirname "$action_file")

            # Check for package.json
            if [[ -f "$action_dir/package.json" ]]; then
              echo "[Info] ✅ package.json found"

              # Validate package.json syntax
              if node -e "JSON.parse(require('fs').readFileSync('$action_dir/package.json', 'utf8'))" 2>/dev/null; then
                echo "[Info] ✅ package.json syntax is valid"
              else
                echo "[Error] ❌ package.json syntax is invalid in $action_dir/package.json"
                exit 1
              fi

              # Check for main entry point
              main_file=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$action_dir/package.json', 'utf8')).main || '')" 2>/dev/null)
              if [[ -n "$main_file" && -f "$action_dir/$main_file" ]]; then
                echo "[Info] ✅ Main entry point found: $main_file"
              else
                echo "[Error] ❌ Main entry point not found or invalid in $action_dir/package.json"
                echo "[Debug] Expected main file: $main_file"
                exit 1
              fi

              # Install dependencies and run tests if they exist
              if grep -q '"test"' "$action_dir/package.json"; then
                echo "[Info] Installing dependencies and running tests..."
                cd "$action_dir"
                npm install
                npm test
              else
                echo "[Info] No tests configured in package.json"
              fi
            else
              echo "[Error] ❌ package.json not found in $action_dir"
              exit 1
            fi
          done
        else
          echo "[Info] No JavaScript actions found"
          echo "js_actions_found=false" >> $GITHUB_OUTPUT
        fi

    - name: Test composite actions
      shell: bash
      run: |
        echo "[Info] 🔧 Testing composite actions..."

        # Find composite actions
        composite_actions=""
        for action_file in ${{ steps.find-changes.outputs.files }}; do
          if [[ -n "$action_file" && -f "$action_file" ]]; then
            action_type=$(grep -A1 "runs:" "$action_file" | grep "using:" | awk '{print $2}' | tr -d '"')
            if [[ "$action_type" == "composite" ]]; then
              echo "[Info] Found composite action: $action_file"
              composite_actions="$composite_actions $action_file"
            fi
          fi
        done

        if [[ -n "$composite_actions" ]]; then
          echo "[Info] Composite actions to test: $composite_actions"
          for action_file in $composite_actions; do
            echo "[Info] Testing composite action: $action_file"

            # Validate YAML structure
            if grep -q "runs:" "$action_file" && grep -q "using:" "$action_file" && grep -q "steps:" "$action_file"; then
              echo "[Info] ✅ Valid composite action structure"
            else
              echo "[Error] ❌ Invalid composite action structure"
              exit 1
            fi

                        # Test shell scripts in steps
            echo "[Info] Testing shell scripts..."
            # Use awk to find shell scripts with line numbers and handle multi-line scripts
            awk '
              /shell:/ {
                in_shell = 1;
                shell_line = NR;
                next
              }
              in_shell && /run:/ {
                if ($0 ~ /run: \|/) {
                  # Multi-line script starting with |
                  in_script = 1;
                  script_start_line = NR;
                  script = "";
                  next;
                } else {
                  # Single-line script
                  script = substr($0, index($0, "run: ") + 5);
                  if (length(script) > 0) {
                    print "LINE:" NR ":" script;
                  }
                  in_shell = 0;
                }
              }
              in_script {
                if ($0 ~ /^[[:space:]]*[a-zA-Z]/ && !($0 ~ /^[[:space:]]*-/)) {
                  # End of script (new step or section)
                  if (length(script) > 0) {
                    print "LINE:" script_start_line ":" script;
                  }
                  in_script = 0;
                  in_shell = 0;
                } else {
                  # Continue collecting script lines
                  script = script "\n" $0;
                }
              }
            ' "$action_file" | while IFS=: read -r prefix line_num script; do
              if [[ "$prefix" == "LINE" ]]; then
                echo "[Debug] Validating script at line $line_num: $script"
                # Basic shell syntax check
                if echo "$script" | bash -n 2>/dev/null; then
                  echo "[Info] ✅ Script syntax is valid (line $line_num)"
                else
                  echo "[Error] ⚠️  Script syntax may have issues in $action_file at line $line_num"
                  echo "[Debug] Script: $script"
                fi
              fi
            done
          done
        else
          echo "[Info] No composite actions found"
        fi

    - name: Test container actions
      shell: bash
      run: |
        echo "[Info] 🐳 Testing container actions..."

        # Find container actions
        container_actions=""
        for action_file in ${{ steps.find-changes.outputs.files }}; do
          if [[ -n "$action_file" && -f "$action_file" ]]; then
            action_type=$(grep -A1 "runs:" "$action_file" | grep "using:" | awk '{print $2}' | tr -d '"')
            if [[ "$action_type" == "docker" ]]; then
              echo "[Info] Found container action: $action_file"
              container_actions="$container_actions $action_file"
            fi
          fi
        done

        if [[ -n "$container_actions" ]]; then
          echo "[Info] Container actions to test: $container_actions"
          for action_file in $container_actions; do
            echo "[Info] Testing container action: $action_file"

            # Check for Dockerfile
            action_dir=$(dirname "$action_file")
            if [[ -f "$action_dir/Dockerfile" ]]; then
              echo "[Info] ✅ Dockerfile found: $action_dir/Dockerfile"
              # Basic Dockerfile validation - check for common syntax issues
              if grep -q "^FROM " "$action_dir/Dockerfile"; then
                echo "[Info] ✅ Dockerfile has valid FROM instruction"
              else
                echo "[Error] ❌ Dockerfile missing FROM instruction in $action_dir/Dockerfile"
                exit 1
              fi

              # Check for common Dockerfile issues
              if grep -q "COPY\|ADD" "$action_dir/Dockerfile"; then
                echo "[Info] ✅ Dockerfile has file operations"
              else
                echo "[Error] ⚠️  Dockerfile may be missing file operations in $action_dir/Dockerfile"
              fi
            else
              echo "[Error] ❌ Dockerfile not found in $action_dir (expected: $action_dir/Dockerfile)"
              exit 1
            fi
          done
        else
          echo "[Info] No container actions found"
        fi
