name: 'Python Account Mapping'
description: 'Determines AWS account number using Python logic'
inputs:
  changed-files:
    description: 'List of changed files (from changed-files action)'
    required: true
  environment:
    description: 'Environment (dev/prod)'
    required: true
outputs:
  account-number:
    description: 'Determined AWS account number'
    value: ${{ steps.account.outputs.account_number }}
runs:
  using: 'composite'
  steps:
    - name: Determine account number using Python
      id: account
      run: |
        python3 << 'EOF'
        import os
        import sys
        
        # Get inputs from environment variables
        changed_files = os.environ.get('CHANGED_FILES', '')
        environment = os.environ.get('ENVIRONMENT', '')
        
        # Account mappings (like Python dictionaries!)
        account_mappings = {
            'prod_account_number': {
                'src': 'prod_src_account',
                'tests': 'prod_tests_account',
                'default': 'prod_default_account'
            },
            'dev_account_number': {
                'src': 'dev_src_account',
                'tests': 'dev_tests_account',
                'default': 'dev_default_account'
            }
        }
        
        # Determine account type based on changed files
        if '^src/' in changed_files:
            account_type = 'src'
        elif '^tests/' in changed_files:
            account_type = 'tests'
        else:
            account_type = 'default'
        
        # Get account number from mapping
        if environment in account_mappings:
            account_number = account_mappings[environment][account_type]
        else:
            print(f"Error: Unknown environment '{environment}'", file=sys.stderr)
            sys.exit(1)
        
        # Output for GitHub Actions
        print(f"account_number={account_number}")
        print(f"Environment: {environment}", file=sys.stderr)
        print(f"Changed files: {changed_files}", file=sys.stderr)
        print(f"Account type: {account_type}", file=sys.stderr)
        print(f"Determined account number: {account_number}", file=sys.stderr)
        EOF
      env:
        CHANGED_FILES: ${{ inputs.changed-files }}
        ENVIRONMENT: ${{ inputs.environment }}
      shell: bash 