name: 'JavaScript Action with Python'
description: 'JavaScript action that executes Python logic'
inputs:
  changed-files:
    description: 'List of changed files'
    required: true
  environment:
    description: 'Environment'
    required: true
outputs:
  account-number:
    description: 'Account number'
    value: ${{ steps.action.outputs.account_number }}
runs:
  using: 'node20'
  main: 'index.js' 