name: Pre-Commit Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit-reusable.yml
    with:
      python-version: '3.x'
      fetch-depth: '0'
