name: Test Changed Actions & Workflows

on:
  push:
    branches: [master, dev]
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
  pull_request:
    branches: [master, dev]
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'

jobs:
  test-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # fetch full history and all branches so merge-base works
          fetch-depth: 0

      - name: Find changed action and workflow files
        id: changes
        uses: ./.github/actions/changed-files
        with:
          pattern: |
            .github/actions/**/action.yml
            .github/workflows/*.yml

      - name: Debug changed files output
        if: ${{ steps.changes.outputs.files != '' }}
        run: |
          echo "Changed files detected by the action:"
          echo "${{ steps.changes.outputs.files }}"
          echo "Filtering to ensure only relevant files are processed."

      - name: Lint changed workflows
        if: ${{ steps.changes.outputs.files != '' }}
        run: |
          echo "🔍 Linting changed workflow files..."
          # install actionlint
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint_linux_amd64.tar.gz \
            | tar -xz && sudo mv actionlint /usr/local/bin/
          FOUND_WORKFLOW=0
          for wf in ${{ steps.changes.outputs.files }}; do
            if [[ $wf == .github/workflows/*.yml ]]; then
              echo "  • $wf"
              actionlint -f github-actions "$wf"
              FOUND_WORKFLOW=1
            fi
          done
          if [ $FOUND_WORKFLOW -eq 0 ]; then
            echo "No workflow files found in the changed files list."
          fi

      - name: Test changed actions
        if: ${{ steps.changes.outputs.files != '' }}
        run: |
          echo "🧪 Testing changed custom actions..."
          FOUND_ACTION=0
          for file in ${{ steps.changes.outputs.files }}; do
            if [[ $file == .github/actions/*/action.yml ]]; then
              dir=$(dirname "$file")
              echo "  • Processing action in $dir"
              if grep -qE "runs:\s*using:\s*composite" "$file"; then
                echo "    – Composite action detected, please test locally with 'act'"
              elif grep -qE "runs:\s*using:\s*node" "$file"; then
                echo "    – JavaScript action detected, running Jest tests"
                cd "$dir"
                npm install --silent
                npm test
                cd -
              else
                echo "    – Unknown action type, skipping"
              fi
              FOUND_ACTION=1
            fi
          done
          if [ $FOUND_ACTION -eq 0 ]; then
            echo "No action files found in the changed files list."
          fi 