name: Integration Test for changed-files Action and python-ci Workflow

on:
  push:
    branches: [master, dev]
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
  pull_request:
    branches: [master, dev]
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changes.outputs.files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          fetch-tags: true

      - name: Find changed action and workflow files
        id: changes
        uses: ./.github/actions/changed-files
        with:
          pattern: |
            ^\.github/actions/.*/.*
            ^\.github/workflows/.*\.yml$

      - name: Show changed files
        run: |
          echo "${{ steps.changes.outputs.files }}"

  lint-workflows:
    needs: find-changes
    runs-on: ubuntu-latest
    if: contains(needs.find-changes.outputs.files, '.github/workflows/')
    steps:
      - uses: actions/checkout@v4
      - name: Install actionlint
        run: |
          GO111MODULE=on go install github.com/rhysd/actionlint/cmd/actionlint@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          actionlint --version
      - name: Lint changed workflows
        run: |
          for wf in ${{ needs.find-changes.outputs.files }}; do
            if [[ $wf =~ ^\.github/workflows/.*\.yml$ ]]; then
              echo "Linting $wf"
              actionlint -f github-actions "$wf"
            fi
          done

  test-changed-files-action:
    needs: find-changes
    runs-on: ubuntu-latest
    if: contains(needs.find-changes.outputs.files, '.github/actions/changed-files/')
    steps:
      - uses: actions/checkout@v4
      - name: Run changed-files action as integration test
        uses: ./.github/actions/changed-files
        with:
          pattern: '^README\.md$'

  test-python-ci-workflow:
    needs: find-changes
    runs-on: ubuntu-latest
    if: contains(needs.find-changes.outputs.files, '.github/workflows/python-ci.yml')
    steps:
      - uses: actions/checkout@v4
      - name: Call python-ci workflow as a test
        uses: ./.github/workflows/python-ci.yml
        with:
          python-version: '3.11'
          run-integration-tests: false 